[ord_main_win]
headless = False
user_data_dir000 = C:\Users\99458\AppData\Local\Google\Chrome\User Data
user_data_dir001 = C:\Users\99458\AppData\Local\Google\Chrome\User Data001
user_data_dir002 = C:\Users\99458\AppData\Local\Google\Chrome\User Data002
user_data_dir003 = C:\Users\99458\AppData\Local\Google\Chrome\User Data003
chrome_driver = chromedriver.exe
uuid = ZLG69HTOQKIRZTRK
# 01校园网，02互联网
net_mode = 02

[ord_main_linux]
headless = True
user_data_dir = C:\Users\99458\AppData\Local\Google\Chrome\User Data
chrome_driver = chromedriver_linux
# 01校园网，02互联网
net_mode = 02